name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Obfuscator
        run: npm install javascript-obfuscator

      - name: Obfuscate from local source file
        run: |
          node -e "
            const JavaScriptObfuscator = require('javascript-obfuscator');
            const fs = require('fs');
            const path = require('path');
            
            const sourceFileName = '明文源吗';
            const outputFileName = 'worker.js';
            const sourceFilePath = path.join(process.cwd(), sourceFileName);

            if (!fs.existsSync(sourceFilePath)) {
              console.error('错误：在路径 \'' + sourceFilePath + '\' 未找到源文件。请确保您的仓库根目录有名为 \'明文源吗\' 的文件。');
              process.exit(1);
            }

            const originalCode = fs.readFileSync(sourceFilePath, 'utf8');

            if (!originalCode || originalCode.trim().length === 0) {
              console.error('错误：源文件 ' + sourceFileName + ' 为空。');
              process.exit(1);
            }

            // --- 这是一个非常简单的混淆配置 ---
            const obfuscationOptions = {
                compact: true,                // 压缩代码
                stringArray: true,            // 启用字符串数组
                stringArrayEncoding: ['base64'], // 将字符串数组用 base64 编码
                stringArrayThreshold: 0.8,    // 80% 的字符串都会被加密
                identifierNamesGenerator: 'hexadecimal', // 变量名改成 0x...
                
                // --- 以下所有复杂选项均被禁用 ---
                controlFlowFlattening: false, // 禁用控制流平坦化 (修复错误)
                renameGlobals: false,         // 禁用全局重命名 (修复错误)
                deadCodeInjection: false,
                numbersToExpressions: false,
                splitStrings: false,
                transformObjectKeys: false,
                selfDefending: false,
                debugProtection: false
            };

            const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
            
            fs.writeFileSync(path.join(process.cwd(), outputFileName), obfuscatedCode, 'utf8');
            console.log('成功将 \'' + sourceFileName + '\' 混淆并保存至 \'' + outputFileName + '\'。');
          "

      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 'worker.js'
          if git diff --staged --quiet; then
            echo "No changes to commit, the obfuscated file is already up-to-date."
          else
            git commit -m "少年你相信光吗"
            git push
          fi
